server:
  port: 8089
  servlet:
    context-path: /

mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-enums-package: com.gravity.demo.common.enums
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: qjl
    password: qjl2133!
    url: jdbc:p6spy:mysql://49.233.87.14:3306/gravity?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 15
      minimum-idle: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址--公司地址
    host: 49.233.87.14
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password: qjl3312
    # 连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
  ## Elasticsearch配置文件（必须）
  ## 该配置和Elasticsearch的elasticsearch.yml中的配置信息有关
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch_qijunlin
#      cluster-nodes: 127.0.0.1:9300
#      #是否开启本地存储
#      repositories:
#        enabled: true
#https://www.jianshu.com/p/de838a665eec
elasticsearch:
  ip: localhost:9200

