server:
  port: 8081
  servlet:
    context-path: /
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://127.0.0.1:3306/gravity?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 15
      minimum-idle: 10
      data-source-properties:
       cachePrepStmts: true
       prepStmtCacheSize: 250
       prepStmtCacheSqlLimit: 2048
       useServerPrepStmts: true
       useLocalSessionState: true
       rewriteBatchedStatements: true
       cacheResultSetMetadata: true
       cacheServerConfiguration: true
       elideSetAutoCommits: true
       maintainTimeStats: false
